language: groovy
sudo: false

dist: trusty
jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    sources:
    - r-packages-trusty
    packages:
    - r-base-dev

branches:
  only:
    - master
notifications:
  email:
    - umayrh@gmail.com
